---------------------------------------------
-- table: salesman
---------------------------------------------


-- 1. select all the salespeople. Return salesman_id, name, city, commission with the percent sign (%)
SELECT salesman_id, name, city, CONCAT(commission*100, '%') AS commission
FROM salesman;


---------------------------------------------
-- table: orders
---------------------------------------------

-- 2. find the number of orders booked for each day. Return the result in a format like "For 2001-10-10 there are 15 orders".".
SELECT CONCAT('For ', ord_date, ' there are ', COUNT(ord_no), ' orders') AS result
FROM orders
GROUP BY ord_date;

-- 3. find all the orders. Sort the result-set in ascending order by ord_no. Return all fields.
SELECT *
FROM orders
ORDER BY ord_no ASC;

-- 4. find all the orders. Sort the result-set in descending order by ord_date. Return all fields. 
SELECT *
FROM orders
ORDER BY ord_no DESC;


-- 5. find all the orders. Sort the result-set in descending order by ord_date and purch_amt. Return all fields.
SELECT *
FROM orders
ORDER BY ord_no DESC, purch_amt DESC;

-- 7. calculates the maximum purchase amount generated by each salesperson for each order date. 
-- Sort the result-set by salesperson id and order date in ascending order. Return salesperson id, order date and maximum purchase amount. 
SELECT salesman_id, ord_date, MAX(purch_amt) AS max_purch_amt
FROM orders
GROUP BY salesman_id, ord_date
ORDER BY salesman_id ASC, ord_date ASC;

-- 9. counts the unique orders and the highest purchase amount for each customer. 
-- Sort the result-set in descending order on 2nd field. 
-- Return customer ID, number of distinct orders and highest purchase amount by each customer. 
SELECT customer_id, COUNT(DISTINCT ord_no) AS num_orders, MAX(purch_amt) AS max_purch_amt
FROM orders
GROUP BY customer_id
ORDER BY 2 DESC;

-- 10. calculate the summation of purchase amount, total commission (15% for all salespeople) by each order date. 
-- Sort the result-set on order date. Return order date, summation of purchase amount and commission.
-- commission 佣金 is a fee paid to a salesperson or agent for their services in facilitating a transaction
SELECT ord_date, SUM(purch_amt) AS total_purch_amt, SUM(purch_amt*0.15) AS total_commission
FROM orders
GROUP BY ord_date
ORDER BY ord_date ASC;



---------------------------------------------
-- table: customer
---------------------------------------------



-- 6. find all the customers. Sort the result-set by customer_id. Return cust_name, city, grade.
SELECT cust_name, city, grade
FROM customer
ORDER BY customer_id;


-- 8. find all the customers. Sort the result-set in descending order on 3rd field. Return customer name, city and grade.
SELECT cust_name, city, grade
FROM customer
ORDER BY 3 DESC;